### ISSUE TITLE
Benutzerrechte Dateimanagement

### ISSUE THREAD

**Issue by zirkai** [premiumcontaothemes/customcatalog#2]
Habe eine Contao 3.3.7 Version im Einsatz und einen Redakteur-Benutzer. Seit CC eingespielt wurde kann dieser keine Bilder in News und Content mehr auswählen. Zugriff auf das Dateimanagement hat der Benutzer aber, er kann auch Ordner erstellen und uploaden. Rechte habe ich überprüft. Habe ich etwas übersehen? Müssen für CC gesondert Rechte angegeben werden? Das Phänomen tritt seit CC auf, ob es direkt Auswirkungen haben kann, kann ich nicht einschätzen.

**Comment by timgatzky** [comment]
Ist es damit verbunden? http://forum.premium-contao-themes.com/forum/module/customcatalog/639-customcatalog-objekte-benutzerrechte-nicht-richtig-einstellbar?p=680#post680

**Comment by timgatzky** [comment]
Ich kann es reproduzieren. Im Log steht:  Invalid news content element ID 123

**Comment by zirkai** [comment]
Bei mir stand im Log 'Not enough permissions to access the modules module'. Versteh nur den Zusammenhang nicht, es ging tatsächlich um die Core-Bilderauswahl beim Teaser der News. Es hatte gar nichts mit CC zutun. Habe jetzt die Frontend-Module freigegeben, jetzt gehts.

**Comment by timgatzky** [comment]
Ok, ja das steht in Verbindung mit dem Zwang in 3.5 jeder Klasse eine Models Klasse zu reservieren, die vom Kern erbt. In der Kern-Datei werden die Rechte geprüft und fehlt da ein Recht bei den Theme-Modulen knallts. Könnte bissel strikt in contao sein.
Ich schau mir das hier aber nochmal genauer an.

**Comment by timgatzky** [comment]
Ok, Fehler gefunden und behoben. Ein kleiner Schnitzer im Bild-Attribut von CE mit großen Wirkungen (das Galerie-Attribute ebenfalls geupdated)

**Comment by zirkai** [comment]
Dangee :)
