### ISSUE TITLE
CC: News Anlage hinzufügen gibt Rechteproblem bei Redakteur

### ISSUE THREAD

**Issue by zirkai** [premiumcontaothemes/customcatalog#3]
Hi Tim,
hab mir eben die neuesten Versionen vom CC geladen, es wurden heute Nacht auch wohl Änderungen eingespielt.
Das gleiche Problem wie bei dem Teaserbild gibt es bei den Anlagen. Beim Teaserbild geht es bei mir, bei den Anlagen schmeißt er den Fehler "tl_content_news::checkAccessToElement".

Auch wenn ich Frontend-Module freigebe geht es nicht. Eine Idee?
Guten Start in die Woche. 
Frohes Schaffen und Gruß, Kai

**Comment by timgatzky** [comment]
fixed in 1.2.6

**Comment by zirkai** [comment]
Ich will ja nicht drängeln, aber wann steht die 1.2.6 zur Verfügung? Hab grad das CC Paket aus dem Kundenbereich geladen, da war es noch nicht drin.
Viele Grüße, Kai 


Werbeagentur Goldener Zirkel GmbH
Mitglied der Allianz deutscher Designer (AGD)

Moltkestr. 39
76133 Karlsruhe

Tel. 0721 754001922
Fax 0721 754001929

k.dold@goldener-zirkel.com
www.goldener-zirkel.com

Geschäftsf. Kai-Sebastian Dold
Handelsregister Mannheim
HRB-Nr. 721354
Ust.ID DE298679177

**Comment by timgatzky** [comment]
http://forum.premium-contao-themes.com/forum/allgemein/728-update-customelements-1-4-5-customcatalog-1-2-6

**Comment by zirkai** [comment]
Hallo Tim,
nach den Updates tritt das Problem noch immer auf bei den Redakteuren, trotz Freigabe der Frontend-Formulare. 
Log: Funktion:	tl_content_news::checkAccessToElement
Haste noch eine Idee?
Frohes Schaffen und Gruß, Kai

**Comment by timgatzky** [comment]
Schick mir mal ein Ticket im PCT Ticketsystem. Ein CE update löst das Problem. CC ist es nicht. Die Version geht im Laufe der kommenden Woche erst an den Start.
