### ISSUE TITLE
Performance - sehr viele Datenbankabfragen

### ISSUE THREAD

**Issue by tj-rising** [premiumcontaothemes/customcatalog#4]
Hi Tim,
Der CustomCatalog erzeugt sehr viele Datenbankabfragen, was die Seite spürbar langsam macht.
Ich hab z.B. 3 Kataloge in einer Installation mit jeweils 10-15 Attributen. Selbst auf Seiten, die nichts mit dem CC zu tun haben (sowohl im BE als auch im FE) werden schon mal mehr als 100 zusätzliche Queries getätigt.
Ein weiteres Beispiel, ein Katalog hat 14 Attribute und insgesamt nur 36 Einträge, im FE ist ein Tagfilter dabei. Im FE werden nun, um diese Liste darzustellen, mehr als 800 Queries getätigt.
Ist da in Zukunft was in Sachen Performance-Optimierung geplant?

**Comment by timgatzky** [comment]
Hast mit Sicherheit ein Haufen Filter-Abhängigkeiten

**Comment by timgatzky** [comment]
Ich werde einige zusätzliche Performance-Schalter in die nächste Version bauen. So braucht es z.B. nicht zwingend die DataContainer Arrays im Frontend.

**Comment by tj-rising** [comment]
Ich bin gespannt auf's nächste Update!
Bin grad in den Endzügen bei einem CC-Projekt und hab grad noch mit diversen andren Dingen zu kämpfen;) Aber sobald das durch ist, werd ich mich genauer mit den Query-Geschichten auseinandersetzen und dann hier berichten.

**Comment by timgatzky** [comment]
Besonders CE wird ein Performance-Kit seitens der Datenbanken bekommen. Natürlich darf die Funktionsweise nicht verloren gehen.
