### ISSUE TITLE
Probleme, wenn man den internen Contao-Cache nutzt

### ISSUE THREAD

**Issue by tj-rising** [premiumcontaothemes/customcatalog#5]
Wenn man den internen Cache aufgebaut hat, macht der CC die Contao-Installation unbrauchbar.
Es werden Extensions nicht mehr geladen, wie z.B. das Notification Center. 
Ausserdem ist mein Hook-Filter nicht mehr vorhanden und es kracht natürlich im Frontend. Kurz in die Liste der Hook-Filter geguckt, es steht nur noch dein "Beispiel-Filter" dort.
Ich geh mal davon aus, dass noch weitere Extensions/Hooks im Cache-Modus vom CC blockiert werden. 
Das ganze ist grad ziemlich dringend, da es in Richtung Live-Gang geht und ich ungern ohne Cache rausgeh.

**Comment by timgatzky** [comment]
Hast deinen internen Cache danach neuaufgebaut?

**Comment by timgatzky** [comment]
Habe es gerade getestet. Keine Probleme mit internem Cache. Habe hier eine 3.5.3 als Umgebung.

**Comment by tj-rising** [comment]
Hi,
hab den Fehler gefunden, das Plugin Notelist ist der Übeltäter.
Ich hab das Plugin nicht aktiviert, weil ich es nicht benötige. Wenn man den IC nutzt und die Notelist nicht benötigt, muss man die Notelist inaktiv setzen oder ganz vom Server kicken.
Ansonsten wird die config.php im system/cache/config - Ordner an dieser Stelle nicht weiter ausgeführt.
Das Notification-Center und einige meiner Module liegen halt dahinter.

    /**
     * Stop here if CE Version is to low or notelist is not active
     */
    if(strlen(strpos(\Environment::getInstance()->scriptName, '/contao/install.php')) < 1)
    {
	    $objPluginFactory = new \PCT\CustomElements\Core\PluginFactory();
	    dump($objPluginFactory::getActivePlugins());
	    if(!in_array('notelist',$objPluginFactory::getActivePlugins()) && \Input::get('do') != 'repository_manager' )
	    {
		    return;
	    }
    }

**Comment by timgatzky** [comment]
Ah das stimmt. Das ist nicht gut.

**Comment by timgatzky** [comment]
Here you go: https://github.com/timgatzky/pct_customelements_plugin_notelist/releases/tag/1.0.6
