### ISSUE TITLE
Filter/Such-Problem im BE-List View im Mulitlanguage-Mode

### ISSUE THREAD

**Issue by tj-rising** [premiumcontaothemes/customcatalog#6]
Hi Tim,
hab gesehen, dass du denn CC geupdated hast und das Filter/Such-Problem im BE-List View gefixed
hast:

    Fixed: Backend filters/search loose value in multilanguage mode due to reload in the language panel (#248)

Leider funktioniert das nicht in den Sortierungsmodi 1 und 2 ,sondern aktuell bei mir nur im Modus 5.1.
In den Modi 1 und 2 wird bei einer Suche immer nur "keine Einträge vorhanden" angezeigt.

Kannst du das reproduzieren? Es geht wie gesagt um einen mehrsprachigen CC.

**Comment by timgatzky** [comment]
In einem mehrsprachigen CC wird die filterung nach den Spracheinträgen jetzt umgangen, wenn einer der Backend-Filter aktiv ist, da Contao beides nicht korrekt versteht.
