### ISSUE TITLE
Sortierungsmodus 5.1 in einem Mulitlanguage CC 1.3.3

### ISSUE THREAD

**Issue by tj-rising** [premiumcontaothemes/customcatalog#7]
Der Sortierungsmodus 5.1 hat in einem ML CC Macken.
Wenn ich z.B. einen Basis-Eintrag anlege, abspeicher und dann über den Sprachenwechsel zu einer
anderen Sprache wechsel, findet zwar ein Reload statt und die neue Sprache ist im Sprachenwechsler sichtbar, allerdings ändert sich die ID nicht und der vorher angelegte Basis-Eintrag wird somit überschrieben.

**Comment by Brubbel66** [comment]
Ich glaube der Fehler ist bekannt und wird im nächsten Update behoben sein (soll diese Woche kommen ;-))
Workaround ist, wenn die neue Sprache oben im Sprachenwähler zu sehen ist, dann noch mal den reload manuell auslösen. Die ID ändert sich und der Eintrag kann editiert werden.
Etwas mühsam aber geht.

**Comment by tj-rising** [comment]
Muss hier was beachten? In meiner Umgebung muss ich jetzt auch bei ML-CCs im Sortierungsmodus 1 den Reload nochmal manuell erzwingen, damit sich die ID ändert.

**Comment by timgatzky** [comment]
Im Listview wird das gesamte Filter-Formular gefeuert.
Im Edit Modus wird der reload angestoßen.

Der Grundaufbau der Mehrsprachig hat sich etwas verändert. Es ist jetzt auch möglich reine Spracheinträge anzulegen.
Und neue Einträge werden nicht sofort angelegt, sondern erst beim Speichern. Solange nicht aktiv gespeichert wurde, wird der Eintrag ggf. wieder gelöscht. Wie es bei Contao der Fall ist, wenn man einen neuen Eintrag über "Neuen Eintrag" oben anlegt. -> so lange wird auch die ID gleich bleiben

**Comment by tj-rising** [comment]
ok, funktioniert irgendwie nicht, hab das Gefühl dass, da ein Session-Problem drin ist.
Angenommen ich will auf die "alte Weise" einen Eintrag anlegen.
1) Basis-Eintrag anlegen
2) im Edit Modus die Sprache wechseln. Jetzt steht auch oben "Die aktive Sprache ist Deutsch"
3. Eintrag befüllen und abspeichern.
-> es wird kein deutscher Eintrag angelegt, sondern der Basiseintrag überschrieben

Wenn ich aber im im Edit Modus die Sprache wechsel und dann einen manuellen Reload auslös
steht oben nicht nur "Die aktive Sprache ist Deutsch", sondern auch "Neuer Spracheintrag für Sprache de" wird beim Speichern angelegt. Und dann geht es erst.

Und wenn ich so mühsam die Einträge angelegt hab, will ich doch im Edit-Modus über die Sprache wechseln, falls ich nochmal was ändern will. Das funktioniert auch nicht. Mal passt der Eintrag nicht zur Sprache und mal kommt die Meldung "Neuer Spracheintrag für Sprache xx" wird beim Speichern angelegt. Das will man ja nicht, wenn man schon die Einträge für jede Sprache gemacht hat
