### ISSUE TITLE
Nach Update auf 1.4.2 SQL-Fehler

### ISSUE THREAD

**Issue by tj-rising** [premiumcontaothemes/customcatalog#8]
Hi Tim,
komme nach dem Update nicht mehr in den Listview im BE:

    Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))' at line 1 (SELECT tl_pct_customelement.* FROM tl_pct_customelement WHERE (SELECT pid FROM tl_pct_customelement_group WHERE id=(SELECT pid FROM tl_pct_customelement_attribute WHERE id=))) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

Hat was mit den Tags (eigene Tabelle) zu tun, in einem anderen CC ohne Tags-Attribut komme ich in den Listview.

Brauchst du noch mehr Infos?

Gruß
Tim

**Comment by timgatzky** [comment]
Wo wird das aufgerufen? Bitte den ganzen Fehlerstrang

**Comment by tj-rising** [comment]
Hab einen CC "Produkte", in dem ein Tags-Attribut mit Referenz auf einen anderen CC "Kategorien" existiert. Wenn ich nun "Produkte" aufruf, kommt statt dem Listview diese Fehlermeldung

    Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))' at line 1 (SELECT tl_pct_customelement.* FROM tl_pct_customelement WHERE (SELECT pid FROM tl_pct_customelement_group WHERE id=(SELECT pid FROM tl_pct_customelement_attribute WHERE id=))) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

    #0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
    #1 system/modules/pct_customelements/PCT/CustomElements/Core/CustomElementFactory.php(67): Contao\Database\Statement->execute()
    #2 system/modules/pct_customelements/PCT/CustomElements/Core/CustomElementFactory.php(288): PCT\CustomElements\Core\CustomElementFactory::find(Array)
    #3 system/modules/pct_customelements/PCT/CustomElements/Core/Attribute.php(1043): PCT\CustomElements\Core\CustomElementFactory::findByAttributeId(NULL)
    #4 system/modules/pct_customelements/PCT/CustomElements/Core/Attribute.php(1339): PCT\CustomElements\Core\Attribute->getCustomElement()
    #5 system/modules/pct_customelements_attribute_tags/PCT/CustomElements/Attributes/Tags/Tags.php(198): PCT\CustomElements\Core\Attribute->hasTranslation('Baumaschinen [d...')
    #6 system/modules/pct_customelements_attribute_tags/PCT/CustomElements/Attributes/Tags/Tags.php(444): PCT\CustomElements\Attributes\Tags->renderCallback('categories', 'a:1:{i:0;s:2:"1...', Object(Contao\BackendTemplate), Object(PCT\CustomElements\Attributes\Tags))
    #7 system/modules/pct_customelements/PCT/CustomElements/Core/Hooks.php(120): PCT\CustomElements\Attributes\Tags->processWildcardValue('a:1:{i:0;s:2:"1...', Object(PCT\CustomElements\Attributes\Tags), '34', 'cc_products')
    #8 [internal function]: PCT\CustomElements\Core\Hooks->processWildcardValue('a:1:{i:0;s:2:"1...', Object(PCT\CustomElements\Attributes\Tags), '34', 'cc_products')
    #9 system/modules/pct_customelements/PCT/CustomElements/Core/Hooks.php(77): call_user_func_array(Array, Array)
    #10 system/modules/pct_customelements_plugin_customcatalog/PCT/CustomElements/Plugins/CustomCatalog/Helper/DcaHelper.php(491): PCT\CustomElements\Core\Hooks::callstatic('processWildcard...', Array)
    #11 system/modules/core/drivers/DC_Table.php(4665): PCT\CustomElements\Plugins\CustomCatalog\Helper\DcaHelper->generateListLabels(Array, '34', Object(Contao\DC_Table), Array)
    #12 system/modules/core/drivers/DC_Table.php(378): Contao\DC_Table->listView()
    #13 system/modules/core/classes/Backend.php(639): Contao\DC_Table->showAll()
    #14 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('produkte')
    #15 contao/main.php(20): Contao\BackendMain->run()
    #16 {main}

**Comment by timgatzky** [comment]
Das sieht mehr nach einem veralteten oder leeren Attribut Datensatz aus:
#3 system/modules/pct_customelements/PCT/CustomElements/Core/Attribute.php(1043): PCT\CustomElements\Core\CustomElementFactory::findByAttributeId(NULL)

**Comment by tj-rising** [comment]
Es lag an der Wildcard. Da hab ich die Tags erstmal rausgenommen. Wundert mich nur, weil es vor dem Update ging.

**Comment by timgatzky** [comment]
Kann es lokal nicht reproduzieren.
